import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ProviderConnection } from '../shared/api'

/**
 * Bun's reader for user-added model endpoints (v10 `connections` — see
 * `ProviderConnection`). Every connection lives in ONE `<baseDir>/providers.json`: there
 * are a handful, always read together (the picker needs all of them). The service's
 * provider owner (`service/ProviderData.swift`) is the only writer since LKM-111
 * removed the Bun twin: saves, removals, the key cipher and `secretFor`.
 *
 * KEY DISCIPLINE: the encrypted key blob lives only in the on-disk record and is never
 * part of `ProviderConnection`. `list()`/`get()` return the renderer-safe shape
 * (`hasKey` only); plaintext only ever comes back from the owner, in main.
 */
export interface ProviderStore {
  /** Every connection, newest last (creation order), ALWAYS key-stripped. */
  list: () => ProviderConnection[]
  get: (id: string) => ProviderConnection | null
}

/**
 * Ids are generated by the owner, but a hand-edited or IPC-supplied id reaches `get`
 * too. The same charset the owner and sessions-store enforce.
 */
const SAFE_ID = /^[A-Za-z0-9_-]{1,128}$/

/** The disk shape: a connection plus its encrypted key. `hasKey` is derived on
 *  read, never stored, so the two can't disagree. */
type StoredConnection = Omit<ProviderConnection, 'hasKey'> & { secret?: string }

interface StoreFile {
  version: 1
  connections: StoredConnection[]
}

/** Well past anything the owner writes (a key blob is ~hundreds of bytes) — a
 *  bigger file is corrupt, not merely big. */
const MAX_STORE_BYTES = 512 * 1024

export function createProviderStore(baseDir: string): ProviderStore {
  const file = join(baseDir, 'providers.json')

  // Every field `toPublic` passes through has to be checked here, not just the
  // ones used for lookup: a truncated or hand-edited file with `"models": "gpt-5"`
  // would otherwise reach `choices()`, which iterates it — filling the model picker
  // with one entry per CHARACTER, under an `undefined` group heading.
  const isStored = (v: unknown): v is StoredConnection => {
    const c = v as StoredConnection | null
    return (
      !!c &&
      typeof c.id === 'string' &&
      SAFE_ID.test(c.id) &&
      typeof c.baseUrl === 'string' &&
      typeof c.label === 'string' &&
      Array.isArray(c.models) &&
      c.models.every((m) => typeof m === 'string')
    )
  }

  /** No file yet, or one that cannot be understood, reads as empty; the owner keeps an
   *  unparseable file as `.corrupt` before its next write. */
  const load = (): StoredConnection[] => {
    let raw: string
    try {
      raw = readFileSync(file, 'utf8')
    } catch {
      return []
    }
    if (raw.length > MAX_STORE_BYTES) return []
    try {
      const parsed = JSON.parse(raw) as StoreFile
      if (!parsed || !Array.isArray(parsed.connections)) return []
      // Drop individual junk entries without failing the whole read — one
      // hand-edited record shouldn't hide every other connection.
      return parsed.connections.filter(isStored)
    } catch {
      return []
    }
  }

  const toPublic = (c: StoredConnection): ProviderConnection => ({
    id: c.id,
    label: c.label,
    preset: c.preset,
    baseUrl: c.baseUrl,
    // Coerced on read, so a hand-edited providers.json carrying the retired 'chat'
    // value can't propagate an unusable connection downstream.
    wireApi: 'responses',
    models: c.models,
    hasKey: !!c.secret
  })

  const list = (): ProviderConnection[] => load().map(toPublic)

  const get = (id: string): ProviderConnection | null => {
    if (!SAFE_ID.test(id)) return null
    const found = load().find((c) => c.id === id)
    return found ? toPublic(found) : null
  }

  return { list, get }
}

/**
 * Blank a secret out of a string before it can be shown or persisted.
 *
 * The last line of defence for the "a key never reaches an error message" rule.
 * Needed wherever text we didn't compose can carry one — notably a spawned CLI's
 * stderr, whose environment holds the key. A no-op when `secret` is empty, so
 * callers can apply it unconditionally.
 */
export function scrubSecret(message: string, secret: string | null | undefined): string {
  return secret && message.includes(secret) ? message.split(secret).join('***') : message
}

/**
 * Do two endpoint URLs share a protocol+host+port?
 *
 * This is the single rule deciding whether a stored API key may follow a URL
 * edit — used by the owner's save (drop the secret when the origin changes) and by the
 * catalog probe (refuse a stored key aimed at a different host). A credential
 * belongs to the host it was issued for; letting it follow an arbitrary URL
 * change is how a caller that cannot READ a key still gets it SENT somewhere.
 * Unparseable input reads as different, so the failure mode is "ask for the key
 * again" rather than "send it anyway".
 */
export function sameOrigin(a: string, b: string): boolean {
  try {
    return new URL(a).origin === new URL(b).origin
  } catch {
    return false
  }
}

/**
 * The catalog URL for an endpoint root: `<baseUrl>/models`.
 *
 * Deliberately NOT clever about `/v1`. An OpenAI-compatible baseUrl already IS
 * the versioned root (`https://ai-gateway.vercel.sh/v1`), and the same string is
 * later handed to the Codex SDK — so injecting a `/v1` the user didn't type would
 * make the probe validate a URL the actual turns never call, turning "Connect
 * worked" into a mystery 404 at chat time. A root that already ends in `/v1`
 * therefore needs no special case, and one that doesn't is taken at its word.
 * Tolerates trailing slashes, and is idempotent if the user pastes the full
 * `/models` URL (a natural thing to copy out of a provider's docs).
 */
export function modelsUrl(baseUrl: string): string {
  const trimmed = (baseUrl ?? '').trim().replace(/\/+$/, '')
  if (/\/models$/i.test(trimmed)) return trimmed
  return `${trimmed}/models`
}

/**
 * Model ids out of a `/models` response body. The standard OpenAI shape is
 * `{data:[{id}]}`, but "OpenAI-compatible" hosts are only compatible up to a
 * point: some answer with `{models:[…]}` and some with a bare array, and entries
 * come as either objects or plain strings. Accept all of them, ignore anything
 * malformed (never throw — this parses a hostile/unknown body), and return sorted
 * unique ids so the dialog's checkbox list has a stable order.
 */
export function parseModelCatalog(json: unknown): string[] {
  const root = json as { data?: unknown; models?: unknown } | null
  const entries = Array.isArray(json)
    ? json
    : Array.isArray(root?.data)
      ? root.data
      : Array.isArray(root?.models)
        ? root.models
        : []
  const ids = new Set<string>()
  for (const entry of entries) {
    let id: unknown
    if (typeof entry === 'string') id = entry
    else if (entry && typeof entry === 'object') {
      // `name` covers the local-runtime shapes (Ollama/LM Studio native lists),
      // which otherwise parse to an empty catalog.
      const e = entry as { id?: unknown; name?: unknown }
      id = typeof e.id === 'string' ? e.id : e.name
    }
    if (typeof id !== 'string') continue
    const trimmed = id.trim()
    if (trimmed) ids.add(trimmed)
  }
  return [...ids].sort()
}
